### ISSUE TITLE
Repository is now outdated

### ISSUE THREAD

**Issue by Jolg42** [ctrlplusb/prisma2-pg-jest#2]
Hi @ctrlplusb!

Just wanted to open an issue to say that the repository here is outdated since there was some breaking changes in the latest versions.

The [beta version of Prisma 2 is out](https://www.prisma.io/blog/prisma-2-beta-b7bcl0gd8d8e) and it should be a lot more stable now :)

Do you plan to update it or do you need some help maybe?

**Comment by ctrlplusb** [comment]
I have done this finally. 😊

Thanks @Jolg42 💜

**Comment by Jolg42** [comment]
Nice job @ctrlplusb! 😍
